### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by Iyxan23** [y9neon/SketchwareManager#2]
Currently, the wiki and README.md file have examples in kotlin, since not everyone knows kotlin, java examples should also be added

**Comment by y9neon** [comment]
Unfortunately, at the moment Java support is not ready yet, I think the library will be ready before the stable version.

However, I think I'll do it pretty soon.

**Comment by Iyxan23** [comment]
Yeah you do, i've had some pain implementing the library on my app (that is using java) dealing with those coroutines.

**Comment by y9neon** [comment]
I ask you to wait for a little, it is not stable in terms of work anyway. I will try to implement it in the near future.

**Comment by y9neon** [comment]
Java support is ready in the new alpha-2.2.4 release.
So far, only in test mode. Add the following dependency to your Gradle dependencies:
```groovy
implementation 'io.sketchware:java-wrapper:alpha-2.2.4'
```

**Comment by y9neon** [comment]
Recently, I added [Java Tutorial](https://github.com/y9neon/SketchwareManager/tree/master/tutorials/How%20to%20use%20library%20in%20Java).
You can check out it.
