### ISSUE TITLE
help

### ISSUE THREAD

**Issue by poppyblue2** [y9neon/SketchwareManager#9]
so i'm using sketchware to make a music app that takes a picture of your sheet music, scans it and tells the user what the notes are.

i have figured out how they can take a photo from camera or gallery but I don't know how i would get it to scan the photo and add the relevant notes. can anyone help

**Comment by y9san9** [comment]
@poppyblue2 Please close the issue, because it doesn't related to the library. You can join this chat to discuss your question: t.me/sketchware_community
